version: 2

models:

  - name: dim_account
    description: "Dimension table containing customer account information."
    columns:
      - name: account_key
        tests:
          - not_null
          - unique

      - name: account_name
        tests:
          - not_null

  - name: dim_products
    description: "Dimension table containing product information."
    columns:
      - name: product_key
        tests:
          - not_null
          - unique

      - name: product_name
        tests:
          - not_null

  - name: dim_sales_teams
    description: "Dimension table containing sales team information."
    columns:
      - name: sales_agent_key
        tests:
          - not_null
          - unique

      - name: agent_name
        tests:
          - not_null

  - name: fact_sales_pipelines
    description: "Fact table containing sales pipeline information."
    columns:

      - name: opportunity_key
        tests:
          - not_null
          - unique

      - name: account_key
        tests:
          
          - relationships:
              to: ref('dim_account')
              field: account_key

      - name: product_key
        tests:
          
          - relationships:
              to: ref('dim_products')
              field: product_key

      - name: sales_agent_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_sales_teams')
              field: sales_agent_key

      - name: opportunity_id
        tests:
          - not_null
          - unique